class AuthConsts:
    LOGIN_ERROR = "登录失败"
    ACCOUNT_DISABLED = "账号被禁用"
    LOGIN_SUCCESS = "登录成功"
    USERNAME_ALREADY_EXISTS = "用户名已存在"
    EMAIL_ALREADY_EXISTS = "邮箱已经存在"
    REGISTER_SUCCESS = "注册成功"
    INFO_REQUIRED = '用户名密码不能为空'
    REFRESH_SUCCESS = '刷新令牌成功'
    FACEINFO_REQUIRED = '人脸信息缺失'
    FACE_ERROR = '无法校验人脸'
    UPDATE_USER_INFO_SUCCESS = '更新数据成功'
    UPDATE_USER_INFO_FAILURE = '更新数据失败'
    ORIGIN_PASSWORD_WRONG = '原密码错误'
    UPDATE_PASSWORD_SUCCESS = '更新密码成功'
    GET_ENGINEER_SUCCESS = '获取工程师成功'
    GET_USERINFO_SUCCESS = '获取用户信息成功'
    GET_ALL_PERMISSIONS_SUCCESS = '获取权限列表成功'
    GET_ALL_ROLE_PERMISSION_LIST_SUCCESS = '获取角色和权限成功'
    UPDATE_USER_STATUS_SUCCESS='更新用户状态成功'
    SOME_PERM_UPDATE_FAIL='部分权限更新失败'
    ROLE_PERM_UPDATE_SUCCESS='更新角色权限成功'
    SOME_ROLE_UPDATE_FAILURE='部分角色更新失败'
    USER_ROLE_UPDATE_SUCCESS='用户角色更新成功'
    CREATE_ROLE_SUCCESS='创建角色成功'
    DELETE_ROLE_SUCCESS="删除角色成功"