"""make audit log block chain style

Revision ID: 0ea2f6b67776
Revises: a0c4cbf3fa8e
Create Date: 2025-04-14 17:16:57.364829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ea2f6b67776'
down_revision = 'a0c4cbf3fa8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.JSON(),
               nullable=True,
               comment='详细操作')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='详细操作')

    # ### end Alembic commands ###
