"""remove engineer table

Revision ID: 0fca70e8942e
Revises: 3c69ed66439d
Create Date: 2025-05-30 13:36:03.105112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fca70e8942e'
down_revision = '3c69ed66439d'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_constraint('inspection_records_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['executor_id'], ['user_id'], ondelete='SET NULL')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_ibfk_1', type_='foreignkey')
        batch_op.drop_column('engineer_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.CHAR(), nullable=True, comment='M-男, F-女'))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('work_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contact_info', sa.String(length=255), nullable=True))

    op.drop_table('engineers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contact_info')
        batch_op.drop_column('work_years')
        batch_op.drop_column('department')
        batch_op.drop_column('gender')
        batch_op.drop_column('name')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engineer_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key('tasks_ibfk_1', 'engineers', ['engineer_id'], ['engineer_id'], ondelete='SET NULL')

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inspection_records_ibfk_1', 'engineers', ['executor_id'], ['engineer_id'], ondelete='SET NULL')

    op.create_table('engineers',
    sa.Column('engineer_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('gender', mysql.CHAR(length=1), nullable=True, comment='M-男, F-女'),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('work_years', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('contact_info', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='engineers_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('engineer_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
