"""change charset

Revision ID: 12a9263f0e13
Revises: 
Create Date: 2025-04-01 08:33:38.646672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12a9263f0e13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_type',
    sa.Column('typeid', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=True, comment='飞机型号名'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.PrimaryKeyConstraint('typeid'),
    mysql_charset='utf8mb4'
    )
    op.create_table('dictionary',
    sa.Column('dict_key', sa.String(length=50), nullable=False),
    sa.Column('dict_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_key', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_key'], ['dictionary.dict_key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('dict_key'),
    mysql_charset='utf8mb4'
    )
    op.create_table('models',
    sa.Column('model_id', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('model_description', sa.Text(), nullable=True),
    sa.Column('model_aircraft_type_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('model_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_name'),
    mysql_charset='utf8mb4'
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name'),
    mysql_charset='utf8mb4'
    )
    op.create_table('terminal',
    sa.Column('terminal_id', sa.String(length=50), nullable=False),
    sa.Column('terminal_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('terminal_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('faceInfo', sa.Text(), nullable=True, comment='人脸数据信息,可以是人脸的url链接,json等'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='1-启用, 0-禁用'),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('aircraft',
    sa.Column('aircraft_id', sa.String(length=50), nullable=False),
    sa.Column('aircraft_name', sa.String(length=255), nullable=True, comment='飞机名字'),
    sa.Column('age', sa.BigInteger(), nullable=True),
    sa.Column('typeid', sa.String(length=50), nullable=True, comment='飞机型号ID'),
    sa.ForeignKeyConstraint(['typeid'], ['aircraft_type.typeid'], ),
    sa.PrimaryKeyConstraint('aircraft_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('engineers',
    sa.Column('engineer_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.CHAR(), nullable=True, comment='M-男, F-女'),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('work_years', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('engineer_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.String(length=50), nullable=False),
    sa.Column('aircraft_id', sa.String(length=50), nullable=False),
    sa.Column('terminal_id', sa.String(length=50), nullable=True),
    sa.Column('estimated_departure', sa.DateTime(), nullable=True, comment='预计起飞'),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=True, comment='预计到达'),
    sa.Column('flight_status', sa.String(length=50), nullable=True),
    sa.Column('actual_departure', sa.DateTime(), nullable=True, comment='实际起飞'),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True, comment='实际到达'),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.aircraft_id'], ),
    sa.ForeignKeyConstraint(['approval_status'], ['dictionary.dict_key'], ),
    sa.ForeignKeyConstraint(['flight_status'], ['dictionary.dict_key'], ),
    sa.ForeignKeyConstraint(['health_status'], ['dictionary.dict_key'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.terminal_id'], ),
    sa.PrimaryKeyConstraint('flight_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('flight_id', sa.String(length=50), nullable=False),
    sa.Column('estimated_start', sa.DateTime(), nullable=True),
    sa.Column('estimated_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('engineer_id', sa.String(length=50), nullable=True),
    sa.Column('task_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.engineer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_status'], ['dictionary.dict_key'], ),
    sa.PrimaryKeyConstraint('task_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('inspection_records',
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('inspection_name', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.String(length=50), nullable=False, comment='所属任务编号'),
    sa.Column('executor_id', sa.String(length=50), nullable=True, comment='执行工程师'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='完成百分比'),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('inspection_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['engineers.engineer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_status'], ['dictionary.dict_key'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('blockchain_transactions',
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=True),
    sa.Column('transaction_hash', sa.String(length=255), nullable=False, comment='交易哈希'),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('transaction_data', sa.Text(), nullable=True, comment='传递信息'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_records.inspection_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status'], ['dictionary.dict_key'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('inspection_projects',
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=True),
    sa.Column('model_id', sa.String(length=50), nullable=True, comment='使用的模型'),
    sa.Column('project_points', mysql.JSON(), nullable=True, comment='各个点位,检测结果,检测图url,json数据'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_images', mysql.JSON(), nullable=True, comment='参考图片路径或URL的JSON数组'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_records.inspection_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_projects')
    op.drop_table('blockchain_transactions')
    op.drop_table('inspection_records')
    op.drop_table('tasks')
    op.drop_table('flights')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('engineers')
    op.drop_table('audit_logs')
    op.drop_table('aircraft')
    op.drop_table('users')
    op.drop_table('terminal')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('models')
    op.drop_table('dictionary')
    op.drop_table('aircraft_type')
    # ### end Alembic commands ###
