"""fix auth

Revision ID: 16a6baadab25
Revises: 12a9263f0e13
Create Date: 2025-04-01 11:36:05.828228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16a6baadab25'
down_revision = '12a9263f0e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('action')
        batch_op.drop_column('resource')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('action', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
