"""add admin to task

Revision ID: 3c69ed66439d
Revises: 556dc156365b
Create Date: 2025-05-30 13:17:57.533039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c69ed66439d'
down_revision = '556dc156365b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['user_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
