"""update inspection table

Revision ID: 535d45010c0f
Revises: 92e3c480f872
Create Date: 2025-04-17 12:40:55.073044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '535d45010c0f'
down_revision = '92e3c480f872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_item',
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=True),
    sa.Column('item_point', mysql.JSON(), nullable=True, comment='单个点位,送测照片,点位坐标+照片Json'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('result', mysql.JSON(), nullable=True, comment='检测结果'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_records.inspection_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_charset='utf8mb4'
    )
    op.drop_table('inspection_projects')
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.String(length=50), nullable=True, comment='使用的模型'))
        batch_op.add_column(sa.Column('reference_image_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['model_id'])
        batch_op.create_foreign_key(None, 'aircraft_reference_image', ['reference_image_id'], ['image_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reference_image_id')
        batch_op.drop_column('model_id')

    op.create_table('inspection_projects',
    sa.Column('project_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('inspection_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('model_id', mysql.VARCHAR(length=50), nullable=True, comment='使用的模型'),
    sa.Column('project_points', mysql.JSON(), nullable=True, comment='各个点位,检测结果,检测图url,json数据'),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('reference_images', mysql.JSON(), nullable=True, comment='参考图片路径或URL的JSON数组'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_records.inspection_id'], name='inspection_projects_ibfk_1'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], name='inspection_projects_ibfk_2'),
    sa.PrimaryKeyConstraint('project_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('inspection_item')
    # ### end Alembic commands ###
