"""change model relation with inspection

Revision ID: 556dc156365b
Revises: 10f9c48a1821
Create Date: 2025-04-22 21:34:41.007671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '556dc156365b'
down_revision = '10f9c48a1821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.String(length=50), nullable=True, comment='使用的模型'))
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['model_id'])

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_constraint('inspection_records_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('inspection_records_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'aircraft_reference_image', ['reference_image_id'], ['image_id'], ondelete='CASCADE')
        batch_op.drop_column('model_id')

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_api_path', sa.Text(), nullable=True))
        batch_op.drop_column('model_aircraft_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_aircraft_type_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('model_api_path')

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', mysql.VARCHAR(length=50), nullable=True, comment='使用的模型'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inspection_records_ibfk_4', 'models', ['model_id'], ['model_id'])
        batch_op.create_foreign_key('inspection_records_ibfk_5', 'aircraft_reference_image', ['reference_image_id'], ['image_id'])

    with op.batch_alter_table('inspection_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###
