"""remove old block chain table

Revision ID: 77ac3d43706c
Revises: 535d45010c0f
Create Date: 2025-04-17 13:38:35.400952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77ac3d43706c'
down_revision = '535d45010c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockchain_transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_transactions',
    sa.Column('transaction_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('inspection_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('transaction_hash', mysql.VARCHAR(length=255), nullable=False, comment='交易哈希'),
    sa.Column('block_number', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('transaction_data', mysql.TEXT(), nullable=True, comment='传递信息'),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_records.inspection_id'], name='blockchain_transactions_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status'], ['dictionary.dict_key'], name='blockchain_transactions_ibfk_2'),
    sa.PrimaryKeyConstraint('transaction_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
