"""make audit log block chain style1

Revision ID: 92e3c480f872
Revises: 0ea2f6b67776
Create Date: 2025-04-14 17:18:35.954426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92e3c480f872'
down_revision = '0ea2f6b67776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=True, comment='区块链交易哈希'))
        batch_op.add_column(sa.Column('blockchain_block_number', sa.BigInteger(), nullable=True, comment='区块链块高度'))
        batch_op.add_column(sa.Column('blockchain_operator', sa.String(length=42), nullable=True, comment='区块链操作者地址'))
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('resource_type')
        batch_op.drop_column('details')
        batch_op.drop_column('resource_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('details', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('resource_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('blockchain_operator')
        batch_op.drop_column('blockchain_block_number')
        batch_op.drop_column('blockchain_tx_hash')

    # ### end Alembic commands ###
