"""change image_json type to json

Revision ID: a0c4cbf3fa8e
Revises: e19932ad21b4
Create Date: 2025-04-12 20:57:13.667806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0c4cbf3fa8e'
down_revision = 'e19932ad21b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft_reference_image', schema=None) as batch_op:
        batch_op.alter_column('image_json',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_comment='图片json格式点位',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft_reference_image', schema=None) as batch_op:
        batch_op.alter_column('image_json',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_comment='图片json格式点位',
               existing_nullable=True)

    # ### end Alembic commands ###
