"""增加飞机底图表

Revision ID: c783e492c426
Revises: 16a6baadab25
Create Date: 2025-04-11 22:12:58.280713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c783e492c426'
down_revision = '16a6baadab25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_reference_image',
    sa.Column('image_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='图片ID'),
    sa.Column('image_name', sa.String(length=255), nullable=True, comment='图片名'),
    sa.Column('image_description', sa.Text(), nullable=True, comment='图片描述'),
    sa.Column('image_json', sa.Text(), nullable=True, comment='图片json格式点位'),
    sa.Column('aircraft_id', sa.String(length=50), nullable=True, comment='飞机ID'),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.aircraft_id'], ),
    sa.PrimaryKeyConstraint('image_id'),
    mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aircraft_reference_image')
    # ### end Alembic commands ###
