"""update foreignkey ondelete cascade

Revision ID: e19932ad21b4
Revises: c783e492c426
Create Date: 2025-04-12 16:07:53.330420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19932ad21b4'
down_revision = 'c783e492c426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_constraint('aircraft_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'aircraft_type', ['typeid'], ['typeid'], ondelete='cascade')

    with op.batch_alter_table('aircraft_reference_image', schema=None) as batch_op:
        batch_op.drop_constraint('aircraft_reference_image_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'aircraft', ['aircraft_id'], ['aircraft_id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft_reference_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aircraft_reference_image_ibfk_1', 'aircraft', ['aircraft_id'], ['aircraft_id'])

    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aircraft_ibfk_1', 'aircraft_type', ['typeid'], ['typeid'])

    # ### end Alembic commands ###
