name: Publish Docker Image
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Sync Gitee to GitHub" ]   # 名字必须与第一个工作流的 name 对应
    types:
      - completed
jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.0.0
        with:
          ref: dev_backend
          fetch-depth: 0

      - name: Set up QEMU (optional for multi‑arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ridiculousbuffalo/large-aircraft-backend:latest
