name: Sync Gitee to GitHub

on:
  schedule:
    - cron: '0 */8 * * *' # 每8小时触发一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 确保 GITHUB_TOKEN 有写入权限

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # 不使用默认凭据，我们手动配置
          fetch-depth: 0 # 获取所有历史记录和分支

      - name: Setup SSH for Gitee
        run: |
          mkdir -p ~/.ssh
          if [ -z "${{ secrets.GITEE_SSH_KEY }}" ]; then
            echo "Error: GITEE_SSH_KEY is empty!"
            exit 1
          else
            echo "GITEE_SSH_KEY is not empty, writing to file..."
            echo "${{ secrets.GITEE_SSH_KEY }}" > ~/.ssh/id_rsa
          fi
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        continue-on-error: true

      - name: Test SSH Connection to Gitee
        run: |
          ssh -T git@gitee.com
        continue-on-error: true

      - name: Clone Gitee Repository
        run: |
          git clone --mirror git@gitee.com:chai-xiaoxiexie/large_passenger_aircraft.git gitee-repo
      - name: Push to GitHub
        run: |
          cd gitee-repo
          # 设置 Git 用户信息
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 添加 GitHub 远程仓库，使用 HTTPS 和 GITHUB_TOKEN 认证
          git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/RidiculousBuffal/Graduation-project.git
          # 推送所有分支
          git push github --all
          # 推送所有标签
          git push github --tags